# fly.toml file generated for fullstackopen2022-phonebook-pipeline on 2023-04-01T16:34:39+03:00

app = "fullstackopen2022-phonebook-pipeline"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "arn"
processes = []

[env]
  PORT = "8080"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    interval = 10000
    grace_period = "10s"
    method = "get"
    path = "/health"
    protocol = "http"
    restart_limit = 0
    timeout = 2000
    tls_skip_verify = false
    [services.http_checks.headers]

[deploy]
  release_command = "npm run build:ui"

[processes]
  app = "node index.js"

[build]
  [build.args]
    NODE_VERSION = "16.19.1"