POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Testi ukko",
    "number": "asd"
}

###

GET http://localhost:3001/api/persons/


###

POST https://intense-mountain-40451.herokuapp.com/api/persons
Content-Type: application/json

{
    "name": "asddf",
    "number": "123d4"
}

###

PUT http://localhost:3001/api/persons/61e2a36e07080b08d2399227
Content-Type: application/json

{
    "name": "Jannu",
    "number": "1234678"
}
